
service: Api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ap-south-1
  profile: default
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "*" 
custom:
  autoswagger:
     apiType: 'http'  
     swaggerFiles: ['docs/users.json']
     schemes: ['http']
     basePath: '/dev'


functions:
  - ${file(./handlers/createUsers.yml)}
  - ${file(./handlers/readUsers.yml)}
  - ${file(./handlers/updateUsers.yml)}
  - ${file(./handlers/deleteUsers.yml)}

resources:
  - ${file(./sources/users.yml)}

package:
  exclude:
    - 'node_modules/**'

plugins:
  - serverless-offline
  - serverless-auto-swagger