// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "Api",
    "version": "1"
  },
  "paths": {
    "/createUsers": {
      "post": {
        "summary": "create",
        "description": "",
        "tags": [
          "Users"
        ],
        "operationId": "create.post.createUsers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Userspost"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/getUsers": {
      "get": {
        "summary": "readall",
        "description": "",
        "tags": [
          "Users"
        ],
        "operationId": "readall.get.getUsers",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "query",
            "name": "Depart",
            "type": "string",
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/updateUsers/{id}": {
      "put": {
        "summary": "update",
        "description": "",
        "tags": [
          "Users"
        ],
        "operationId": "update.put.updateUsers/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Userspost"
            }
          },
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/deleteUsers/{id}": {
      "delete": {
        "summary": "delete",
        "description": "",
        "tags": [
          "Users"
        ],
        "operationId": "delete.delete.deleteUsers/{id}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Userspost": {
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "Depart": {
          "type": "string"
        }
      },
      "example": {
        "Name": "Bharathkumar",
        "Depart": "MD"
      }
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "http"
  ]
};