
  Resources:
    UsersDynamoDBTable:
     Type: AWS::DynamoDB::Table
     Properties:
       AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: isActive
            AttributeType: S
          - AttributeName: createdAt
            AttributeType: S
       KeySchema:
          - AttributeName: id
            KeyType: HASH
       GlobalSecondaryIndexes:
        - IndexName: ACTIVEINDEX
          KeySchema:
            - AttributeName: isActive
              KeyType: HASH
            - AttributeName: createdAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
       TableName: testing_user
       BillingMode: PAY_PER_REQUEST 